{"uuid": "89897a18-4ffe-4120-a768-c2a268968e25", "children": ["b430ffaa-11bf-4408-94c6-f9eab78a3814"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "adbutils.errors.AdbError: Can't find any android device/emulator\n", "trace": "  File \"/Users/duole-b-01/UI/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/duole-b-01/UI/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/Users/duole-b-01/UI/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/duole-b-01/UI/venv/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/Users/duole-b-01/UI/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/Users/duole-b-01/UI/venv/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/duole-b-01/UI/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/duole-b-01/UI/venv/lib/python3.12/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/Users/duole-b-01/UI/src/tests/app_logininterface_test.py\", line 19, in driver\n    driver = u2.connect()  # 连接手机，若电脑只连接了一部手机，则不需要设备信息\n             ^^^^^^^^^^^^\n  File \"/Users/duole-b-01/UI/venv/lib/python3.12/site-packages/uiautomator2/__init__.py\", line 947, in connect\n    return connect_usb(serial)\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/Users/duole-b-01/UI/venv/lib/python3.12/site-packages/uiautomator2/__init__.py\", line 962, in connect_usb\n    serial = adbutils.adb.device()\n             ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/duole-b-01/UI/venv/lib/python3.12/site-packages/adbutils/__init__.py\", line 102, in device\n    raise AdbError(\"Can't find any android device/emulator\")\n"}, "start": 1758800383190, "stop": 1758800383200}], "start": 1758800383190, "stop": 1758800383262}